home:
    pattern:   /
    defaults:  { _controller: yourAppBundle:Home:index }

base:
    pattern:   /
    defaults:  { _controller: yourAppBundle:Home:index }


login:
    pattern:   /login
    defaults:  { _controller: yourAppBundle:Auth:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
