security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        static:
            pattern:  ^/(css|font|images|img|js|media)/
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                check_path:            login_check
                login_path:            login
                username_parameter:    _email
                password_parameter:    _password
                target_path_parameter: _target_path
                use_referer:           true
            logout:
                path:   logout
                target: home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
